version: '2'
services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
  kvd:
    container_name: kvd
    privileged: true
    image: lvk.sh/kvd:latest
    environment:
    - REDIS_HOST=kevin