- name: Create install directory
  file:
    path: /opt/kvd
    state: directory
    owner: "pi"
  become: true

- name: Install compose file
  template:
    src: files/docker-compose.yml
    dest: /opt/kvd/docker-compose.yml
    owner: "pi"
  notify: restart kvd
  become: true