- name: Update repo's
  apt:
    update_cache: true
  changed_when: false
- name: Install Basic Packages
  apt:
    name:
      - apt-transport-https
      - net-tools
      - curl
      - pass
      - gnupg2
      - htop
      - tmux
      - git
      - python3-dev
      - python3-setuptools
      - python3-pip
- name: Change hostname
  hostname:
    name: kevin
- name: ETC Hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.1.1               kevin'
  become: true